version: '3.7'

services:
  localstack:
    image: localstack/localstack:3.2
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
      - SERVICES=lambda,s3, ec2
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/localstack_root:/var/lib/localstack  
      - ./localstack/localstack_home:/home/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  default:
    name: localstack